version: "3.8"

services:
  sqlserver:
    build: ./database
    container_name: webscrape-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - //TRUENAS/Misc_storage/database-data/test:/var/lib/postgresql/data
      - ./database/transform:/docker-entrypoint-initdb.d
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    driver: bridge
