# Use the official Microsoft SQL Server image
FROM postgres:latest

# Set environment variables for default setup
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase2

# Expose PostgreSQL port
EXPOSE 5432
